version: '3.8'

services:
  flux-generator:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HF_HUB_ENABLE_HF_TRANSFER=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: apple
              count: all
              capabilities: [gpu]
    restart: unless-stopped 